name: pfe_project
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  http_parser: ^3.0.0
  flutter:
    sdk: flutter
  provider: ^4.3.2+3
  dio : ^3.0.10
  flutter_secure_storage: ^3.3.5



  
  flutter_dialogflow: ^0.1.3
  http: ^0.12.2

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_lints: ^2.0.1
flutter_native_splash:
      color: "#42a5f5"
      image: images/splash.png
      android_gravity: fill

  
flutter:

  
  uses-material-design: true

 
  assets:
  - images/

  
  